Change test approach so it is easier to distribute files (no expected/ dir)

diff --git a/runtest b/runtest
--- a/runtest
+++ b/runtest
@@ -1,7 +1,19 @@
 #!/bin/sh
 
-# Run test of user-union
-# Give it the "-a" parameter to ACCEPT the last test results as expected.
+# Run test of user-union. Takes 1 parameter, the srcdir.
+# Invoke "user_union" in test mode, with overlay of "./overlay" on "/",
+# to run the script "testscript".  Summarize the results in "overlay_results"
+# and do a diff with "expected_results".
+
+if [ "$#" -ne 1 ] ; then
+  echo "Must provide exactly one argument (the source directory)" >&2
+  exit 1
+elif [ -z "$1" ] ; then
+  echo "Argument must not be empty" >&2
+  exit 1
+fi
+
+srcdir="$1"
 
 # Remove 'space', so filenames with spaces work well.
 IFS="$(printf '\n\t')"
@@ -10,9 +22,8 @@ tab="$(printf '\t')"
 newline="$(printf '\nX')"
 newline="${newline%X}"
 
-
 startdir="$(pwd)"
-overlay="/tmp/redir"
+overlay="${startdir}/overlay"
 underlay="/"
 
 PATH="$startdir:$PATH"
@@ -21,47 +32,9 @@ PATH="$startdir:$PATH"
 # nonunion="${nonunion}${newline}/a${tab}/b${tab}/c"
 # nonunion="${newline}/tmp${newline}/home"
 
-# Report on every filesystem object in currect directory, down.
-# TODO: This currently requires GNU extensions (find -printf),
-# need an easy portable way to print data about files.
-reporter() {
-  find .  -exec "$startdir"/fso_stat {} + | sort
-}
-
-# Are we *accepting* the results?
-if [ "$1" = "" ] ; then
-  echo "Need a parameter"
-  exit 1
-fi
-
-if [ "$1" = "-a" ] ; then
-  accept=true
-  shift
-fi
-
-srcdir="$1"
-expected="$1/expected"
-
-if [ ! -d "$expected" ]
-then
-  echo "Can't find expected results directory $expected"
-  exit 1
-fi
-
-if [ "$accept" = "true" ] ; then
-  if [ ! -d "$overlay" ]
-  then
-    echo "Can't find overlay directory $overlay"
-    exit 1
-  fi
-  echo "Accepting results in $overlay as expected; copying to $expected."
-  rsync -a "$overlay/" "$expected/"
-  exit 0
-fi
-
-
 rm -fr "$overlay"
-mkdir "$overlay" || ( echo "Failed to create $overlay" ; exit 1 )
+mkdir -p "$overlay" || \
+  ( echo "Failed to create overlay directory $overlay" ; exit 1 )
 
 echo "About to run tests!"
 
@@ -70,7 +43,7 @@ export MALLOC_CHECK_=3
 
 # Run the main body of tests:
 ./user-union -t -a "$overlay" "$underlay" -i /home -i /tmp -i /var/tmp \
-  ./testscript
+  "${srcdir}/testscript"
 
 # Also do a simple test with run-redir-union, basically a smoke test
 # to make sure it can be run at all:
@@ -88,11 +61,16 @@ echo
 echo "Tests done.  Comparing to find differences with the expected results:"
 
 
-(cd "$overlay" ; reporter ) > ".overlay_results"
-(cd "$expected" ; reporter ) > ".expected_results"
+# TODO: This currently requires GNU extensions (find -printf),
+# need an easy portable way to print data about files.
+reporter() {
+  find .  -exec fso_stat {} + | sort
+}
 
 
-if diff -u ".expected_results" ".overlay_results"
+(cd "$overlay" ; reporter ) > "overlay_results"
+
+if diff -u "expected_results" "overlay_results"
 then
   # TODO: Compare the permissions
   echo "No differences. All tests passed!"
